import { ComponentFixture, TestBed } from '@angular/core/testing';

import { JerseysComponent } from './jerseys.component';

// auto-generated by Angular
describe('JerseysComponent', () => {
  let component: JerseysComponent;
  let fixture: ComponentFixture<JerseysComponent>;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [JerseysComponent]
    });
    fixture = TestBed.createComponent(JerseysComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
