import { ComponentFixture, TestBed } from '@angular/core/testing';

import { JerseyDetailComponent } from './jersey-detail.component';

// auto-generated by Angular
describe('JerseyDetailComponent', () => {
  let component: JerseyDetailComponent;
  let fixture: ComponentFixture<JerseyDetailComponent>;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [JerseyDetailComponent]
    });
    fixture = TestBed.createComponent(JerseyDetailComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
